### ISSUE TITLE
Cannot download CT scan data or 3D models

### ISSUE THREAD

**Issue by yiqunma** [facebookresearch/CT2Hair#4]
The following error appears when clicking on the data download links:
![image](https://github.com/facebookresearch/CT2Hair/assets/40863480/81f312d1-ef52-426f-9877-6d7fdbce2fa4)

**Comment by jihwanahn** [comment]
I have the same problem.

**Comment by giljoonam** [comment]
We're looking into this problem. Thank you for your patience.

**Comment by giljoonam** [comment]
The links should work now. Can you try again?

**Comment by yiqunma** [comment]
Just downloaded. Thanks.
