### ISSUE TITLE
Misaligned head and strands?

### ISSUE THREAD

**Issue by kenshi84** [facebookresearch/CT2Hair#8]
When visualizing the outputs using https://github.com/Jhonve/HairStrandsRendering, it seems that the provided head meshes `data/HeadModels/MannequinHead{A,B}/head.obj` and the output strands are somehow misaligned (see screenshot below). Can this be fixed?

![Screen Shot 2023-08-21 at 12 41 52](https://github.com/facebookresearch/CT2Hair/assets/1090150/310dc6c8-4158-4823-9177-5f26fd585b46)

**Comment by Jhonve** [comment]
The reason is the head model is a template model which will be used to fit the scalp in the following steps, and the hair models were scanned and reconstructed in different coordinate systems.
[In our code base](https://github.com/facebookresearch/CT2Hair/blob/23a81474d02466473bea00f847950a900f6eaf8e/CT2Hair/interp.py#L34), we will export a fitted head mesh in the interpolation step, and the exported head will align the corresponding strands.

**Comment by kenshi84** [comment]
For anyone interested, following the suggestion above, I wrote a simple script that does the fitting:

```python
import os
import argparse
import cv2
import numpy as np
import sys
from pyhocon import ConfigFactory

sys.path.append('CT2Hair/')

from utils.meshutils import read_mesh, process_head_model

parser = argparse.ArgumentParser()
parser.add_argument('--conf', type=str, default='conf/data/Curly.conf')
parser.add_argument('--datapath', type=str, default='data')
k_args = parser.parse_args()

if __name__ == '__main__':
    conf_text = open(k_args.conf).read()
    conf_text = conf_text.replace('DATAPATH', k_args.datapath)
    conf = ConfigFactory.parse_string(conf_text)
    conf_text = conf_text.replace('CASENAME', conf['output']['name'])
    conf = ConfigFactory.parse_string(conf_text)

    head_mesh = read_mesh(conf['head']['head_path'])
    head_texture = cv2.imread(conf['head']['head_scalp_tex'])
    head_mesh, scalp_mesh, scalp_faces_idx = process_head_model(head_mesh, head_texture, 
                                                                conf['head']['roots_path'],
                                                                np.array(conf['head']['target_face_base'], dtype=np.float32),
                                                                is_deformation=True)
    if not os.path.exists(conf['output']['dir']):
        os.makedirs(conf['output']['dir'])
    head_write = head_mesh.export(os.path.join(conf['output']['dir'], f"{conf['output']['name']}_head.ply"))
```
